# Generated by Django 2.2.28 on 2022-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221117_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cheading',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cheading1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cheading2',
            field=models.TextField(null=True),
        ),
    ]
