# Generated by Django 2.2.28 on 2022-11-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221117_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
