# Generated by Django 2.2.28 on 2022-11-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('published_date', models.DateField()),
                ('heading', models.CharField(max_length=255, null=True)),
                ('cheading', models.TextField(null=True)),
                ('heading1', models.CharField(max_length=255, null=True)),
                ('cheading1', models.TextField(null=True)),
                ('heading2', models.CharField(max_length=255, null=True)),
                ('cheading2', models.TextField(null=True)),
                ('blog_img', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
