# Generated by Django 2.2.28 on 2022-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221111_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('Fashion', 'Fashion'), ('Devices', 'Devices'), ('Pharmecy', 'Pharmecy'), ('Beauty', 'Beauty'), ('Computer & Accessories', 'Computer & Accessories'), ('Car, Cycle & Motorbike', 'Car, Cycle & Motorbike'), ('Grocery', 'Grocery')], default='', max_length=50),
        ),
    ]
